<a href="https://colab.research.google.com/github/RicAwesome95/CC19/blob/main/ArmandoR_DuayC_SolivenD_SolomonV_CC19_Preprocessing_Disease_Diagnosis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd #Import the pandas library for data analysis

In [16]:
url = "https://raw.githubusercontent.com/RicAwesome95/CC19/refs/heads/main/disease_diagnosis.csv"
df = pd.read_csv(url) #Load the Titanic dataset from a CSV file into a DataFrame https://www.kaggle.com/datasets/yasserh/titanic-dataset
df.head()

,Patient_ID,Age,Gender,Symptom_1,Symptom_2,Symptom_3,Heart_Rate_bpm,Body_Temperature_C,Blood_Pressure_mmHg,Oxygen_Saturation_%,Diagnosis,Severity,Treatment_Plan
0,1,74,Male,Fatigue,Sore throat,Fever,69,39.4,132/91,94,Flu,Moderate,Medication and rest
1,2,66,Female,Sore throat,Fatigue,Cough,95,39.0,174/98,98,Healthy,Mild,Rest and fluids
2,3,32,Male,Body ache,Sore throat,Fatigue,77,36.8,136/60,96,Healthy,Mild,Rest and fluids
3,4,21,Female,Shortness of breath,Headache,Cough,72,38.9,147/82,99,Healthy,Mild,Rest and fluids
4,5,53,Male,Runny nose,Sore throat,Fatigue,100,36.6,109/106,92,Healthy,Mild,Rest and fluids

In [17]:
print("ALL")
print(df) #Display the entire DataFrame

print("FIRST 10")
print(df.head(10)) #Display the first 10 rows of the dataset

print("LAST 10")
print(df.tail(10)) #Display the last 10 rows of the dataset

ALL
      Patient_ID  Age  Gender            Symptom_1    Symptom_2  \
0              1   74    Male              Fatigue  Sore throat
1              2   66  Female          Sore throat      Fatigue
2              3   32    Male            Body ache  Sore throat
3              4   21  Female  Shortness of breath     Headache
4              5   53    Male           Runny nose  Sore throat
...          ...  ...     ...                  ...          ...
1995        1996   23  Female          Sore throat   Runny nose
1996        1997   75    Male              Fatigue        Cough
1997        1998   79    Male              Fatigue   Runny nose
1998        1999   56  Female                Cough  Sore throat
1999        2000   45  Female              Fatigue    Body ache

                Symptom_3  Heart_Rate_bpm  Body_Temperature_C  \
0                   Fever              69                39.4
1                   Cough              95                39.0
2                 Fatigue              77                36.8
3                   Cough              72                38.9
4                 Fatigue             100                36.6
...                   ...             ...                 ...
1995  Shortness of breath              96                38.2
1996          Sore throat              68                36.1
1997                Fever              73                36.7
1998             Headache              67                39.1
1999                Fever             111                35.8

     Blood_Pressure_mmHg  Oxygen_Saturation_%   Diagnosis  Severity  \
0                 132/91                   94         Flu  Moderate
1                 174/98                   98     Healthy      Mild
2                 136/60                   96     Healthy      Mild
3                 147/82                   99     Healthy      Mild
4                109/106                   92     Healthy      Mild
...                  ...                  ...         ...       ...
1995             116/113                   98     Healthy      Mild
1996             166/113                   97        Cold      Mild
1997              91/103                   95     Healthy      Mild
1998              128/73                   91  Bronchitis    Severe
1999              127/78                   94     Healthy      Mild

                      Treatment_Plan
0                Medication and rest
1                    Rest and fluids
2                    Rest and fluids
3                    Rest and fluids
4                    Rest and fluids
...                              ...
1995                 Rest and fluids
1996                 Rest and fluids
1997                 Rest and fluids
1998  Hospitalization and medication
1999                 Rest and fluids

[2000 rows x 13 columns]
FIRST 10
   Patient_ID  Age  Gender            Symptom_1            Symptom_2  \
0           1   74    Male              Fatigue          Sore throat
1           2   66  Female          Sore throat              Fatigue
2           3   32    Male            Body ache          Sore throat
3           4   21  Female  Shortness of breath             Headache
4           5   53    Male           Runny nose          Sore throat
5           6   22    Male          Sore throat                Fever
6           7   21    Male          Sore throat              Fatigue
7           8   71    Male             Headache  Shortness of breath
8           9   56  Female  Shortness of breath                Fever
9          10   53    Male                Cough                Fever

    Symptom_3  Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0       Fever              69                39.4              132/91
1       Cough              95                39.0              174/98
2     Fatigue              77                36.8              136/60
3       Cough              72                38.9              147/82
4     Fatigue             100                36.6             109/106
5       Cough              90                39.5              107/92
6       Cough              71                37.5              126/82
7  Runny nose              64                38.6              153/99
8    Headache             103                36.2              152/71
9    Headache              62                39.5             111/104

   Oxygen_Saturation_%   Diagnosis  Severity                  Treatment_Plan
0                   94         Flu  Moderate             Medication and rest
1                   98     Healthy      Mild                 Rest and fluids
2                   96     Healthy      Mild                 Rest and fluids
3                   99     Healthy      Mild                 Rest and fluids
4                   92     Healthy      Mild                 Rest and fluids
5                   93         Flu  Moderate             Medication and rest
6                   93  Bronchitis    Severe  Hospitalization and medication
7                   99     Healthy      Mild                 Rest and fluids
8                   96        Cold      Mild                 Rest and fluids
9                   98         Flu  Moderate             Medication and rest
LAST 10
      Patient_ID  Age  Gender    Symptom_1    Symptom_2            Symptom_3  \
1990        1991   60    Male     Headache    Body ache  Shortness of breath
1991        1992   74    Male      Fatigue        Cough                Fever
1992        1993   77  Female      Fatigue        Fever            Body ache
1993        1994   22  Female        Fever  Sore throat           Runny nose
1994        1995   31  Female   Runny nose  Sore throat            Body ache
1995        1996   23  Female  Sore throat   Runny nose  Shortness of breath
1996        1997   75    Male      Fatigue        Cough          Sore throat
1997        1998   79    Male      Fatigue   Runny nose                Fever
1998        1999   56  Female        Cough  Sore throat             Headache
1999        2000   45  Female      Fatigue    Body ache                Fever

      Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
1990              83                38.2             145/118
1991             102                37.8              140/60
1992             112                39.0             112/107
1993              88                39.9              102/97
1994              93                36.4              139/92
1995              96                38.2             116/113
1996              68                36.1             166/113
1997              73                36.7              91/103
1998              67                39.1              128/73
1999             111                35.8              127/78

      Oxygen_Saturation_%   Diagnosis  Severity  \
1990                   96     Healthy      Mild
1991                   93  Bronchitis    Severe
1992                   98         Flu  Moderate
1993                   90         Flu  Moderate
1994                   99        Cold      Mild
1995                   98     Healthy      Mild
1996                   97        Cold      Mild
1997                   95     Healthy      Mild
1998                   91  Bronchitis    Severe
1999                   94     Healthy      Mild

                      Treatment_Plan
1990                 Rest and fluids
1991  Hospitalization and medication
1992             Medication and rest
1993             Medication and rest
1994                 Rest and fluids
1995                 Rest and fluids
1996                 Rest and fluids
1997                 Rest and fluids
1998  Hospitalization and medication
1999                 Rest and fluids

In [18]:
df.describe() #Show summary statistics of the dataset

,Patient_ID,Age,Heart_Rate_bpm,Body_Temperature_C,Oxygen_Saturation_%
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,48.285000,89.439000,37.741000,94.493500
std,577.494589,17.422616,17.139608,1.309835,2.861827
min,1.000000,18.000000,60.000000,35.500000,90.000000
25%,500.750000,33.000000,75.000000,36.600000,92.000000
50%,1000.500000,49.000000,89.000000,37.700000,95.000000
75%,1500.250000,63.000000,104.000000,38.900000,97.000000
max,2000.000000,79.000000,119.000000,40.000000,99.000000

In [19]:
df.info() #Show DataFrame information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           2000 non-null   int64
 1   Age                  2000 non-null   int64
 2   Gender               2000 non-null   object
 3   Symptom_1            2000 non-null   object
 4   Symptom_2            2000 non-null   object
 5   Symptom_3            2000 non-null   object
 6   Heart_Rate_bpm       2000 non-null   int64
 7   Body_Temperature_C   2000 non-null   float64
 8   Blood_Pressure_mmHg  2000 non-null   object
 9   Oxygen_Saturation_%  2000 non-null   int64
 10  Diagnosis            2000 non-null   object
 11  Severity             2000 non-null   object
 12  Treatment_Plan       2000 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 203.3+ KB

In [20]:
df.shape #Display the number of rows and columns

(2000, 13)

In [21]:
print(df.isnull) #Check for missing values in the dataset

<bound method DataFrame.isnull of       Patient_ID  Age  Gender            Symptom_1    Symptom_2  \
0              1   74    Male              Fatigue  Sore throat
1              2   66  Female          Sore throat      Fatigue
2              3   32    Male            Body ache  Sore throat
3              4   21  Female  Shortness of breath     Headache
4              5   53    Male           Runny nose  Sore throat
...          ...  ...     ...                  ...          ...
1995        1996   23  Female          Sore throat   Runny nose
1996        1997   75    Male              Fatigue        Cough
1997        1998   79    Male              Fatigue   Runny nose
1998        1999   56  Female                Cough  Sore throat
1999        2000   45  Female              Fatigue    Body ache

                Symptom_3  Heart_Rate_bpm  Body_Temperature_C  \
0                   Fever              69                39.4
1                   Cough              95                39.0
2                 Fatigue              77                36.8
3                   Cough              72                38.9
4                 Fatigue             100                36.6
...                   ...             ...                 ...
1995  Shortness of breath              96                38.2
1996          Sore throat              68                36.1
1997                Fever              73                36.7
1998             Headache              67                39.1
1999                Fever             111                35.8

     Blood_Pressure_mmHg  Oxygen_Saturation_%   Diagnosis  Severity  \
0                 132/91                   94         Flu  Moderate
1                 174/98                   98     Healthy      Mild
2                 136/60                   96     Healthy      Mild
3                 147/82                   99     Healthy      Mild
4                109/106                   92     Healthy      Mild
...                  ...                  ...         ...       ...
1995             116/113                   98     Healthy      Mild
1996             166/113                   97        Cold      Mild
1997              91/103                   95     Healthy      Mild
1998              128/73                   91  Bronchitis    Severe
1999              127/78                   94     Healthy      Mild

                      Treatment_Plan
0                Medication and rest
1                    Rest and fluids
2                    Rest and fluids
3                    Rest and fluids
4                    Rest and fluids
...                              ...
1995                 Rest and fluids
1996                 Rest and fluids
1997                 Rest and fluids
1998  Hospitalization and medication
1999                 Rest and fluids

[2000 rows x 13 columns]>

In [22]:
medianAge = df['Age'].median() #Calculate the median of the 'Age' column
print("Median: ", medianAge)

Median:  49.0

In [24]:
medianHeart_Rate_bpm = df['Heart_Rate_bpm'].median() #Calculate the median of the 'Fare' column
print("Median: ", medianHeart_Rate_bpm)

Median:  89.0

In [ ]:
modeEmbarked = df['Embarked'].mode() #Find the mode (most common value) of the 'Embarked' column
print("Mode: ", modeEmbarked)

In [ ]:
df['Age'].fillna(df['Age'].median() , inplace=True) #Fill missing 'Age' values with the median age

In [ ]:
df['Embarked'].fillna(df['Embarked'].mode()[0] , inplace=True) #Fill missing 'Embarked' values with the mode (most frequent value)

In [ ]:
print(df.isnull().sum()) #Check if there are still missing values in the dataset

In [ ]:
df.drop('Cabin', axis=1, inplace=True) #Drop the 'Cabin' column since it has too many missing values

In [ ]:
df.drop_duplicates(inplace=True) #Remove duplicate rows from the dataset

In [ ]:
print(df.head()) #Display the first few rows after cleaning

In [ ]:
import matplotlib.pyplot as plt #Import Matplotlib library for creating plots and visualizations
import seaborn as sns #Import Seaborn library for statistical data visualization

In [ ]:
sns.boxplot(x=df['Age']) #Create a boxplot to visualize the distribution and outliers of the Age column
plt.show() #Display the plotted boxplot

In [ ]:
sns.boxplot(x=df['Fare']) #Create a boxplot to visualize the distribution and outliers of the Fare column
plt.show() #Display the plotted boxplot

In [ ]:
Q1 = df['Age'].quantile(0.25) #Calculate the first quartile (25th percentile) of the Age column
Q3 = df['Age'].quantile(0.75) #Calculate the third quartile (75th percentile) of the Age column
IQR = Q3 = Q1 #Compute the Interquartile Range (IQR), used to detect outliers
lower_bound = Q1 - 1.5 * IQR #Calculate the lower limit for detecting outliers
upper_bound = Q3 + 1.5 * IQR #Calculate the upper limit for detecting outliers

df = df[(df['Age'] >= lower_bound) & (df['Age'] <= upper_bound)] #Filter the dataframe to remove Age values outside the IQR bounds

In [ ]:
Q1 = df['Fare'].quantile(0.25) #Calculate the first quartile (25th percentile) of the Fare column
Q3 = df['Fare'].quantile(0.75) #Calculate the third quartile (75th percentile) of the Fare column
IQR = Q3 - Q1 #Compute the Interquartile Range (IQR), used to detect outliers
lower_bound = Q1 - 1.5 * IQR #Calculate the lower limit for detecting Fare outliers
upper_bound = Q3 + 1.5 * IQR #Calculate the upper limit for detecting Fare outliers

df = df[(df['Fare'] >= lower_bound) & (df['Fare'] <= upper_bound)]  # Remove Fare values outside the IQR range from the dataframe

In [ ]:
from sklearn.preprocessing import MinMaxScaler  #Import MinMaxScaler to normalize numerical data to a range (0–1)
scaler = MinMaxScaler() #Create a MinMaxScaler object for scaling features
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']]) #Scale the Age and Fare columns so their values range between 0 and 1

df.head() #Display the first 5 rows of the dataframe to check the scaled values

In [ ]:
df = pd.get_dummies(df, columns=['Sex', 'Embarked', 'Pclass'], drop_first=True) #Convert categorical variables into numerical dummy/indicator variables

df.head() #Show the first 5 rows to verify the encoded categorical columns

In [ ]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1 #Create a new feature 'family_size' by adding siblings/spouses, parents/children, plus the passenger

df[['SibSp', 'Parch', 'family_size']].head() #Display the related columns to verify the new family_size feature

In [ ]:
from sklearn.decomposition import PCA #Import Principal Component Analysis for dimensionality reduction

features = df.select_dtypes(include=['number']) #Select only numerical columns from the dataframe for PCA

pca = PCA(n_components=3) #Initialize PCA to reduce the dataset into 3 principal components
principal_components = pca.fit_transform(features) #Fit PCA on the numeric data and transform it into principal component values

df_pca = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2', 'PC3']) #Create a new dataframe containing the 3 principal components

df_pca.head() #Display the first 5 rows of the PCA-transformed dataset

In [ ]:
from sklearn.feature_selection import mutual_info_classif #Import function to compute Mutual Information scores for feature selection

X = df.drop(columns=['Survived', 'Name', 'Ticket']) #Create feature set X by removing target column and unnecessary text columns
y = df['Survived'] #Define the target variable (Survived)

mi_scores = mutual_info_classif(X, y) #Calculate Mutual Information scores to measure how much each feature influences the target
mi_scores_df = pd.DataFrame({'Feature': X.columns, 'MI Score': mi_scores}) #Create a dataframe to store feature names with their MI scores

mi_scores_df.sort_values(by='MI Score', ascending=False) #Sort features by MI score in descending order to see the most important features first

In [ ]:
df_final = df[['Survived', 'Sex_male', 'Fare', 'family_size', 'Pclass_3', 'Age', 'SibSp']] #Select important features from the dataset
df_final.head() #preview the first few rows

In [ ]:
df_final.to_csv('titanic_preprocessed.csv', index=False) #Save the preprocessed dataset to a CSV file without the index column
from google.colab import files
files.download('titanic_preprocessed.csv')

In [ ]:
x = df_final.drop(columns=['Survived'])
y = df_final['Survived']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify = y
)

In [ ]:
print("Training Features Shape:", X_ train.shape)
print("Training Labels Shape:", y_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Testing Labels Shape:", y_test.shape)